# If not running interactively, don't do anything (leave this at the top of this file)
[[ $- != *i* ]] && return

# if sudo always results in an incorrect password, the following can fix this issue:
# omarchy-reset-sudo

# All the default Omarchy aliases and functions
source ~/.local/share/omarchy/default/bash/rc

# Add user's private bin to PATH
export PATH="$HOME/.local/bin:$PATH"

# VPN configs (generated by scripts/vpn.sh; may be absent on a fresh machine)
[ -f ~/vpn/.vpnrc ] && source ~/vpn/.vpnrc

alias vim='nvim'
alias vi='nvim'

dotfiles() {
  cd /home/char/dotfiles/ || return
  /home/char/dotfiles/setup.sh
  cd - || return
}

empty-trash() {
  rm -rf $HOME/.local/share/Trash/*
  echo "Trash Emptied."
}

# Conda only for interactive shells
if [ -n "$PS1" ] && [ -f /home/char/miniforge3/etc/profile.d/conda.sh ]; then
    . /home/char/miniforge3/etc/profile.d/conda.sh
fi


# Resolve the repo's default branch (handles main vs master). Prefers the
# remote's HEAD; falls back to whichever of main/master exists locally.
_git_default_branch() {
    local def
    def=$(git symbolic-ref --quiet --short refs/remotes/origin/HEAD 2>/dev/null)
    if [ -n "$def" ]; then
        echo "${def#origin/}"
    elif git show-ref --verify --quiet refs/heads/main; then
        echo main
    else
        echo master
    fi
}

gu() {
    current_branch=$(git rev-parse --abbrev-ref HEAD)
    local default_branch
    default_branch=$(_git_default_branch)

    # Check for changes (including untracked) and stash if any
    STASHED=0
    if ! git diff-index --quiet HEAD -- || [ -n "$(git ls-files --others --exclude-standard)" ]; then
        git stash -u
        STASHED=1
    fi

    git checkout "$default_branch"
    git pull
    git checkout "$current_branch"

    # Only pop if we actually stashed something
    if [ "$STASHED" -eq 1 ]; then
        git stash pop
    fi
    git status
}

gur() {
  gu
  git rebase "$(_git_default_branch)"
}

check() {
    # Check the sha256sum of a file against an expected value
    if [ "$#" -ne 2 ]; then
        echo "Usage: checksha256 <file> <expected_sha256>"
        return 1
    fi

    local file="$1"
    local expected="$2"

    if [ ! -f "$file" ]; then
        echo "Error: file '$file' not found"
        return 1
    fi

    # Validate checksum format (64 hex chars)
    if [[ ! "$expected" =~ ^[A-Fa-f0-9]{64}$ ]]; then
        echo "Error: invalid SHA-256 string"
        return 1
    fi

    echo "$expected  $file" | sha256sum -c -
}

alias chad='NVIM_APPNAME=chad nvim'

emergency() {
  sudo rm /var/reserved-space.img
}

# Prints "== label ==" as a section header (used by diagnose/diagnose_snapshots).
_hr() { echo -e "\n== $* ==\n"; }

diagnose() {
  _hr "df -h /"
  df -h /
  _hr "btrfs filesystem usage /"
  sudo btrfs filesystem usage /
  _hr "btrfs filesystem df / (allocated vs used — explains df/du mismatches)"
  sudo btrfs filesystem df /
  _hr "biggest dirs on /"
  sudo du -xhd1 / 2>/dev/null | sort -h | tail
  _hr "biggest dirs in ~"
  du -xhd1 ~ 2>/dev/null | sort -h | tail
  _hr "biggest individual files on / (>200M)"
  sudo find / -xdev -type f -size +200M -exec du -h {} \; 2>/dev/null | sort -rh | head -20
  if command -v docker >/dev/null && docker info >/dev/null 2>&1; then
    _hr "docker usage (RECLAIMABLE column = safe to prune)"
    docker system df -v
  fi
  _hr "ncdu /"
  sudo ncdu -x /
}

diagnose_snapshots() {
  _hr "snapper -c root list"
  sudo snapper -c root list
  _hr "btrfs quota enable /"
  sudo btrfs quota enable /
  _hr "btrfs quota rescan -w /"
  sudo btrfs quota rescan -w /
  _hr "btrfs qgroup show -p --raw / (sorted by exclusive size)"
  sudo btrfs qgroup show -p --raw / | sort -k3 -h
  _hr "cleanup"
  echo "use sudo snapper -c root delete <num1> <num2> ... to delete snapshots"
}

# Read-only sizes of everything emergency-clean is about to wipe, so you know
# what's reclaimable before running it. Docker gets the most detail since
# images are usually the biggest offender.
disk_hogs() {
  _hr "docker"
  if command -v docker >/dev/null && docker info >/dev/null 2>&1; then
    docker system df
    echo ""
    echo "biggest images:"
    docker image ls --format '{{.Size}}\t{{.Repository}}:{{.Tag}}' | sort -rh | head -10
  else
    echo "not running"
  fi
  _hr "conda pkg cache"
  command -v conda >/dev/null && du -sh ~/miniforge3/pkgs 2>/dev/null
  _hr "~/.cache"
  du -sh ~/.cache 2>/dev/null
  _hr "pacman package cache"
  du -sh /var/cache/pacman/pkg 2>/dev/null
  _hr "systemd journal"
  journalctl --disk-usage
}


# ┌─────────────────────────────────────────────────────────────────────────┐
# │ IN CASE OF EMERGENCY, BREAK GLASS — DISK SPACE IS FULL                     │
# ├─────────────────────────────────────────────────────────────────────────┤
# │ System: btrfs on /dev/mapper/root (/, /home, /var all share it).          │
# │ Snapshots = snapper (config 'root', in /.snapshots) + limine-snapper-sync.│
# │ Full reference notes: ~/disk-space-fixes.md                               │
# │                                                                           │
# │ 1) DIAGNOSE — where did the space go? (run top-down, stop when you find it)│
# │    df -h /                                  # are we actually full?        │
# │    sudo btrfs filesystem usage /            # TRUE btrfs free space        │
# │    sudo du -xhd1 / 2>/dev/null | sort -h | tail -20    # biggest dirs on / │
# │    du -xhd1 ~ 2>/dev/null | sort -h | tail -20         # biggest in $HOME  │
# │    sudo ncdu -x /                           # interactive hunt (pacman -S) │
# │                                                                           │
# │ 2) SNAPSHOTS — diagnose                                                   │
# │    sudo snapper -c root list                # list all snapshots          │
# │    # exact reclaimable space per snapshot (the 'excl' column):            │
# │    sudo btrfs quota enable /                                              │
# │    sudo btrfs quota rescan -w /                                           │
# │    sudo btrfs qgroup show -p --raw / | sort -k3 -h                        │
#      sudo snapper -c root delete 19 20 21
# │                                                                           │
# │    SNAPSHOTS — fix (NEVER delete snapshot 0; keep 1 known-good rollback)  │
# │    sudo snapper -c root delete 19 20        # delete by number(s)         │
# │    sudo snapper -c root delete 30-45        # delete an inclusive range   │
# │    sudo snapper -c root cleanup number      # prune per retention limits  │
# │    # tame future growth: edit limits in /etc/snapper/configs/root         │
# │    #   (NUMBER_LIMIT, TIMELINE_LIMIT_DAILY/WEEKLY/MONTHLY)                 │
# │    # limine-snapper-sync fixes the boot menu automatically after deletes. │
# │                                                                           │
# │ 3) DOCKER — diagnose (you already know how to rm images/containers/cache) │
# │    docker system df                         # totals + RECLAIMABLE by type│
# │    docker system df -v                       # per image/container/volume  │
# │    docker image ls --format '{{.Size}}\t{{.Repository}}:{{.Tag}}' | sort -h│
# │    sudo du -sh /var/lib/docker              # where it all lives          │
# │                                                                           │
# │ 4) OTHER QUICK WINS                                                       │
# │    sudo paccache -rk1                        # pacman cache (pacman-contrib)│
# │    sudo journalctl --vacuum-size=200M        # systemd journal            │
# │    rm -rf ~/.cache/*                          # app caches (rebuilt later)  │
# └─────────────────────────────────────────────────────────────────────────┘

# Manually run the disk-usage check (the timer does this every 4h).
# Prints current usage, then runs the alert (fires a critical notification
# only if over threshold). Pass a threshold to force it, e.g. `diskcheck 1`.
diskcheck() {
  df -h --output=pcent,used,avail,target / | tail -n +1
  # Snapshot space needs root; gather it here (sudo may prompt) and pass it to
  # the alert via env so the notification reports the real size. Needs quota:
  # sudo btrfs quota enable /
  local cnt excl
  read -r cnt excl < <(sudo btrfs qgroup show -p --raw / 2>/dev/null | awk '
    $0 ~ /\.snapshots\/[0-9]+\/snapshot/ { e += $3; n++ } END { printf "%d %d", n+0, e+0 }')
  SNAPSHOT_COUNT="$cnt" SNAPSHOT_EXCL="$excl" \
    DISK_THRESHOLD="${1:-85}" ~/.local/bin/disk-usage-alert \
    && echo "Done (notification fires only when over ${1:-85}%)."
}

# Bytes free on / right now (used by emergency-clean to report freed space).
_avail_bytes() { df -B1 / | tail -1 | awk '{print $4}'; }

# Prints how much a step just freed, given its "before" byte count from _avail_bytes.
_report_freed() {
  local label="$1" before="$2" freed
  freed=$(( $(_avail_bytes) - before ))
  echo "   $label freed: $(numfmt --to=iec --suffix=B "$freed" 2>/dev/null || echo "${freed} bytes")"
}

# Asks "$2 [y/N]"; auto-yeses if $1 (the emergency-clean --yes flag) is 1.
_confirm() {
  local auto="$1" prompt="$2" ans
  [[ "$auto" == 1 ]] && return 0
  read -rp "$prompt [y/N] " ans
  [[ "$ans" == [yY]* ]]
}

# In case of disk emergency: for each offender, show its size, ask y/N, then
# clean it and report what that step actually freed. Interactive (sudo may
# prompt). Pass --yes / -y to auto-confirm every step (e.g. from a script).
emergency-clean() {
  local total_before total_after step_before auto_yes=0
  [[ "${1:-}" == "--yes" || "${1:-}" == "-y" ]] && auto_yes=1

  echo "== Disk before =="
  df -h --output=pcent,used,avail,target /
  total_before=$(_avail_bytes)

  if command -v docker >/dev/null && docker info >/dev/null 2>&1; then
    _hr "docker"
    docker system df
    echo ""
    echo "biggest images:"
    docker image ls --format '{{.Size}}\t{{.Repository}}:{{.Tag}}' | sort -rh | head -10
    if _confirm "$auto_yes" "Prune docker build cache + unused images + stopped containers?"; then
      step_before=$(_avail_bytes)
      docker builder prune -af
      docker image prune -af
      docker container prune -f
      # docker volume prune -f   # DISABLED: deletes unused named volumes = possible DB/data loss. Enable knowingly.
      _report_freed "Docker" "$step_before"
    else
      echo "   skipped"
    fi
  fi

  if command -v conda >/dev/null; then
    _hr "conda pkg cache"
    du -sh ~/miniforge3/pkgs 2>/dev/null
    if _confirm "$auto_yes" "Clean conda caches (tarballs, unused packages; envs untouched)?"; then
      step_before=$(_avail_bytes)
      conda clean -afy
      _report_freed "Conda" "$step_before"
    else
      echo "   skipped"
    fi
  fi

  _hr "~/.cache"
  du -sh ~/.cache 2>/dev/null
  if _confirm "$auto_yes" "Wipe ~/.cache (rebuilt on demand)?"; then
    step_before=$(_avail_bytes)
    rm -rf "${HOME:?HOME unset}/.cache/"* 2>/dev/null
    _report_freed "~/.cache" "$step_before"
  else
    echo "   skipped"
  fi

  _hr "pacman package cache"
  du -sh /var/cache/pacman/pkg 2>/dev/null
  if _confirm "$auto_yes" "Trim pacman cache (keep 1 version per package)?"; then
    step_before=$(_avail_bytes)
    if command -v paccache >/dev/null; then sudo paccache -rk1; else sudo pacman -Sc --noconfirm; fi
    _report_freed "Pacman cache" "$step_before"
  else
    echo "   skipped"
  fi

  _hr "systemd journal"
  journalctl --disk-usage
  if _confirm "$auto_yes" "Vacuum journal down to 200M?"; then
    step_before=$(_avail_bytes)
    sudo journalctl --vacuum-size=200M
    _report_freed "Journal" "$step_before"
  else
    echo "   skipped"
  fi

  _hr "snapshots"
  sudo snapper -c root list
  if _confirm "$auto_yes" "Prune snapshots to retention limit (keeps recent + rollback)?"; then
    step_before=$(_avail_bytes)
    sudo snapper -c root cleanup number || true
    _report_freed "Snapshots" "$step_before"
    echo "   Remaining snapshots:"
    sudo snapper -c root list
  else
    echo "   skipped"
  fi

  echo ""
  echo "== Disk after =="
  df -h --output=pcent,used,avail,target /
  total_after=$(_avail_bytes)
  echo "TOTAL freed this run: $(numfmt --to=iec --suffix=B "$((total_after - total_before))" 2>/dev/null || echo "$((total_after - total_before)) bytes")"

  echo "Biggest remaining dirs in ~/.local:"
  du -xhd1 ~/.local 2>/dev/null | sort -h | tail
}

command -v direnv >/dev/null && eval "$(direnv hook bash)"

# Personal (Charles) work/school functions — installed by scripts/personalize.sh
# only on a "Charles PC"; absent on a generic install.
[ -f ~/.bashrc.personal ] && source ~/.bashrc.personal

eval "$(direnv hook bash)"

# Recolor the terminal per directory tree (work vs personal)
source ~/.config/bash/dir-theme.bash
